2022-01-18 08:00:01 WARNING   * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2022-01-18 08:00:01 INFO      * Running on http://192.168.1.206:3111/ (Press CTRL+C to quit)
2022-01-18 08:00:05 ERROR    Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/nwhittington/nd064_course_1/project/techtrends/app.py", line 66, in metrics
    response=json.dumps({"status":"success","code":0,"data":{"db_connection_count":db_conn_count,"post_count":post_value}}),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/json/__init__.py", line 133, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/json/__init__.py", line 57, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
2022-01-18 08:00:05 INFO     127.0.0.1 - - [18/Jan/2022 08:00:05] "[35m[1mGET /metrics HTTP/1.1[0m" 500 -
2022-01-18 08:02:11 WARNING   * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2022-01-18 08:02:11 INFO      * Running on http://192.168.1.206:3111/ (Press CTRL+C to quit)
2022-01-18 08:02:14 INFO     <sqlite3.Row object at 0x10e5d3bb0>
2022-01-18 08:02:14 ERROR    Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/nwhittington/nd064_course_1/project/techtrends/app.py", line 67, in metrics
    response=json.dumps({"status":"success","code":0,"data":{"db_connection_count":db_conn_count,"post_count":post_value}}),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/json/__init__.py", line 133, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/json/__init__.py", line 57, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
2022-01-18 08:02:14 INFO     127.0.0.1 - - [18/Jan/2022 08:02:14] "[35m[1mGET /metrics HTTP/1.1[0m" 500 -
2022-01-18 08:06:23 WARNING   * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2022-01-18 08:06:23 INFO      * Running on http://192.168.1.206:3111/ (Press CTRL+C to quit)
2022-01-18 08:06:28 INFO     <sqlite3.Row object at 0x10ad93be0>
2022-01-18 08:06:28 ERROR    Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/nwhittington/nd064_course_1/project/techtrends/app.py", line 67, in metrics
    response=json.dumps({"status":"success","code":0,"data":{"db_connection_count":db_conn_count,"post_count":post_value}}),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/json/__init__.py", line 133, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/json/__init__.py", line 57, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
2022-01-18 08:06:28 INFO     127.0.0.1 - - [18/Jan/2022 08:06:28] "[35m[1mGET /metrics HTTP/1.1[0m" 500 -
2022-01-18 08:15:11 WARNING   * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2022-01-18 08:15:11 INFO      * Running on http://192.168.1.206:3111/ (Press CTRL+C to quit)
2022-01-18 08:15:15 INFO     127.0.0.1 - - [18/Jan/2022 08:15:15] "GET /metrics HTTP/1.1" 200 -
